apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: alertmanager-data-pvc
    namespace: prometheus
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: prometheus-data-pvc
    namespace: prometheus
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
